name: nhanes_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - lxml
  - pyreadstat
  - openpyxl
  - scikit-learn
  - pyarrow
  - fastparquet
  - requests
  - beautifulsoup4
  - inquirer
  - python-dotenv
  - mlflow
